name: native_updater
description: Flutter package for prompting users to update with a native dialog
  whether using the app store version or any version at the user's discretion.

version: 0.1.1
homepage: https://github.com/ofload/native_updater

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_update: ^4.0.1
  new_version_plus: ^0.0.9
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/native_updater/images/google_play.png
